---
- name: Create Gitea Namespace
  community.okd.k8s:
    name: gitea
    api_version: v1
    kind: Project
    state: present

- name: Install Gitea Operator
  community.okd.k8s:
    state: present
    src: https://raw.githubusercontent.com/redhat-gpte-devopsautomation/gitea-operator/master/catalog_source.yaml

- name: Switch project 
  command: oc project openshift-operators

- name: Install Gitea Operator Subscription
  command: oc apply -f ./files/gitea-operator-subscription.yml

- name: Install Gitea Operator Instance
  command: oc apply -f ./resources/gitea-operator.yml
