---
- name: Create Gitea Namespace
  command: oc new-project git

- name: Install Gitea Operator
  command: oc apply -f https://raw.githubusercontent.com/redhat-gpte-devopsautomation/gitea-operator/master/catalog_source.yam

- name: Switch project 
  command: oc project openshift-operators

- name: Install Gitea Operator Subscription
  command: oc apply -f ./files/gitea-operator-subscription.yml

- name: Install Gitea Operator Instance
  command: oc apply -f ./resources/gitea-operator.yml
