---
- name: Create Gitea Namespace
  community.okd.k8s:
    name: gitea
    api_version: v1
    kind: Project
    state: present

- name: Install Gitea Operator
  community.okd.k8s:
    state: present
    src: https://raw.githubusercontent.com/redhat-gpte-devopsautomation/gitea-operator/master/catalog_source.yaml