apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-hubcontroller-rest
  namespace: openshift-gitops
spec:
  destination:
    namespace: starterapp-python
    server: https://10.89.114.152:6443
  project: default
  source:
    path: gitops-hubcontroller-rest
    repoURL: https://github.com/cloud-native-robotz-hackathon/devel-bucket.git
    targetRevision: master
  syncPolicy: {}
