apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
data:
  cluster-local: "false"
  console: "true"
  edge: "true"

  name: edge-gateway
  router-console: "true"
  service-controller: "true"
  service-sync: "true"

  console-authentication: openshift
