tcp:
  routers:
    edge-controller:
      rule: "HostSNI(`*`)"
      entryPoints:
        - edge-controller
      service: "edge-controller"

    k8s-api:
      rule: "HostSNI(`*`)"
      entryPoints:
        - k8s-api
      service: "k8s-api"

    ingress-http:
      rule: "HostSNI(`*`)"
      entryPoints:
        - ingress-http 
      service: "ingress-http"

    ingress-https:
      rule: "HostSNI(`*`)"
      entryPoints:
        - ingress-https 
      service: "ingress-https"

  services:
    edge-controller:
      loadBalancer:
        servers:
          - address: "{{ env "HOST_IP" }}:5000"
    k8s-api:
      loadBalancer:
        servers:
          - address: "{{ env "HOST_IP" }}:6443"
    ingress-http:
      loadBalancer:
        servers:
          - address: "{{ env "HOST_IP" }}:80"
    ingress-https:
      loadBalancer:
        servers:
          - address: "{{ env "HOST_IP" }}:443"

