- name: Setup DevSecOps Clusters
  hosts: all
  tasks:  
    - name: Print message
      ansible.builtin.debug:
        msg: Starting Setup
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Ping ok
      ansible.builtin.debug:
        msg: Ping ok
    - name: Create Gitea Namespace
      ansible.builtin.command: oc new-project git
      ignore_errors: yes     
    - name: Install Gitea Operator
      ansible.builtin.command:
        oc apply -f https://raw.githubusercontent.com/redhat-gpte-devopsautomation/gitea-operator/master/catalog_source.yaml
    - name: Switch project 
      ansible.builtin.command:
        oc project openshift-operators
    - name: Copy files 
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ./
      with_fileglob:
      - "./*.yml"
    - name: Install Gitea Operator Subscription
      ansible.builtin.command:
        oc apply -f ./resources/gitea-operator-subscription.yml
    #- name: Copy file with owner and permissions
    #  ansible.builtin.copy:
    #    src: ./gitea-operator.yml
    #    dest: ./gitea-operator.yml      
    - name: Install Gitea Operator Instance
      ansible.builtin.command:
        oc apply -f ./resources/gitea-operator.yml
    #- name: Copy file with owner and permissions
    #  ansible.builtin.copy:
    #    src: ./odf-operator-subscription.yml
    #    dest: ./odf-operator-subscription.yml
    - name: Install Gitea Operator Instance
      ansible.builtin.command:
        oc apply -f https://raw.githubusercontent.com/red-hat-storage/odf-operator/main/config/install/openshift-storage-namespace.yaml
      ignore_errors: yes          
    - name: Install Gitea Operator Instance
      ansible.builtin.command:
        oc apply -f ./resources/odf-operator-subscription.yml    
    

