apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: MAP
    fabric8.io/git-branch: master
    fabric8.io/git-commit: d6149aebca8f2ccd695fb90a1680cd6f8db4b96f
    fabric8.io/git-url: git@github.com:cloud-native-robotz-hackathon/hubcontroller-rest.git
    fabric8.io/scm-tag: booster-parent-23
    fabric8.io/scm-url: https://github.com/openshiftio/hub-controller-live
  labels:
    app: hub-controller-live
    group: de.nexussix.openshift.hackathon
    provider: fabric8
    version: 1.0.0-SNAPSHOT
  name: hub-controller-live
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: hub-controller-live
    group: de.nexussix.openshift.hackathon
    provider: fabric8
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: MAP
        fabric8.io/git-branch: master
        fabric8.io/git-commit: d6149aebca8f2ccd695fb90a1680cd6f8db4b96f
        fabric8.io/git-url: git@github.com:cloud-native-robotz-hackathon/hubcontroller-rest.git
        fabric8.io/scm-tag: booster-parent-23
        fabric8.io/scm-url: https://github.com/openshiftio/hub-controller-live
      creationTimestamp: null
      labels:
        app: hub-controller-live
        group: de.nexussix.openshift.hackathon
        provider: fabric8
        version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: MAP
          valueFrom:
            configMapKeyRef:
              key: MAP
              name: robot-mapping-configmap
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/cloud-native-robotz-hackathon/hubcontroller-rest:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
