# RoleBinding for hubcontroller in the openshift-operators namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hubcontroller-rolebinding
  namespace: openshift-operators
subjects:
  - kind: ServiceAccount
    name: hub-controller
    namespace: hub-controller
roleRef:
  kind: Role
  name: hubcontroller-role
  apiGroup: rbac.authorization.k8s.io
