---

- name: Install Ansible
  become: true
  ansible.builtin.dnf:
    name: ansible
    state: latest

- name: Check for installed dependencies
  pip:
    name: "{{ item }}"
    state: present
  loop: 
    - openshift
    - pyyaml
    - kubernetes

- name: Install roles from Ansible Galaxy
  command: ansible-galaxy collection install community.kubernetes