---

- name: Check for installed dependencies
  become: true
  pip:
    name: "{{ item }}"
    state: present
  loop: 
    - openshift
    - pyyaml
    - kubernetes

- name: Install roles from Ansible Galaxy
  command: ansible-galaxy collection install community.kubernetes