# Default values for service-mesh-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

api_username: admin
api_password: foo

openshift_cluster_ingress_domain: "apps.example.com"
ru_enabled: "False"
ru_repo_url: ""
ru_repo_token: ""

team_robot_map:
  - team: team-demo
    robot_name: demo-robot

