---

- name: Instanciate storage-system
  delay: 60
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition:
      apiVersion: odf.openshift.io/v1alpha1
      kind: StorageSystem
      metadata:
        name: ocs-storagecluster-storagesystem
        namespace: openshift-storage
      spec:
        kind: storagecluster.ocs.openshift.io/v1
        name: ocs-storagecluster
        namespace: openshift-storage