- name: "Create Storage System CRD"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'storage-instance/storagesystemcrd.yml') }}"

- name: "Create Storage System"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'storage-instance/storagesystem.yml') }}"

- name: "Create Storage Cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'storage-instance/storagecluster.yml') }}"

- name: "Wait for OCS Cluster to deploy"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    api_version: "ocs.openshift.io/v1"
    kind: StorageCluster
    name: ocs-storagecluster
    wait: true
    wait_condition:
      reason: ReconcileCompleted
      status: 'True'
      type: Available
    wait_sleep: 10
    wait_timeout: 360

- name: "Create ObjectStore"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'storage-instance/rgw_objectstore.yml') }}"

- name: "Create ObjectStore Route"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'storage-instance/objectstore-route.yml') }}"

- name: "Create StorageClass"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'storage-instance/rgw_storageclass.yml') }}"

- name: "Deploy Ceph Toolbox"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'storage-instance/toolbox.yml') }}"