---

- name: Wait for /var/lib/microshift/resources/kubeadmin/kubeconfig
  ansible.builtin.wait_for:
    path: /var/lib/microshift/resources/kubeadmin/kubeconfig
    state: present
    msg: Timeout to find file kubeconfig

- name: Fetch kubeconfig
  ansible.builtin.fetch:
    src: "/var/lib/microshift/resources/kubeadmin/kubeconfig"
    dest: "kubeconfig-{{ inventory_hostname }}"
    flat: yes

- name: Read kubeconfig
  delegate_to: localhost
  include_vars:
    file: "kubeconfig-{{ inventory_hostname }}"
    name: kubeconfig

- name: Rebuild new kubeconfig
  set_fact:
    kubeconfig: "{{ kubeconfig | combine(fields_to_change, recursive=true) }}"
  vars:
    fields_to_change:
      clusters:
        - name: "{{ inventory_hostname.split('.') | first }}"
          cluster:
            server: "https://{{ inventory_hostname }}:6443"
            insecure-skip-tls-verify: true
      contexts:
        - name: "{{ inventory_hostname.split('.') | first }}"
          context: 
            cluster: "{{ inventory_hostname.split('.') | first }}"
            namespace: "default"
            user: "user"
      current-context: "{{ inventory_hostname.split('.') | first }}"

- name: "Write kubeconfig"
  delegate_to: localhost
  copy:
    content: "{{ kubeconfig | to_nice_yaml }}"
    dest: "kubeconfig-{{ inventory_hostname }}"
