---
- name: Rollout new version of robot-config-service "{{ robot_config_service_version  }}"
  ansible.builtin.git:
    repo: https://github.com/cloud-native-robotz-hackathon/robot-config-service.git
    dest: /opt/robot-config-service
    version: "{{ robot_config_service_version  }}"
    force: true
  register: git_result

- name: Rollout environment file
  ansible.builtin.copy:
    content: |
      RCS_GIT_REPO={{ rcs_git_repo }}
      RCS_GH_TOKEN={{ rcs_gh_token }}

      RCS_HUBCONTROLLER_USER={{ rcs_hubcontroller_user }}
      RCS_HUBCONTROLLER_PASSWORD={{ rcs_hubcontroller_password }}

      SERVICE_STARTUP_DELAY=0

    dest: /etc/default/robot-config-service
    mode: '0644'

- name: Install systemd.service
  ansible.builtin.copy:
    remote_src: true
    src: /opt/robot-config-service/robot-config-service.service
    dest: /etc/systemd/system/robot-config-service.service
    mode: '0644'

- name: Enable robot-config-service service
  ansible.builtin.systemd:
    name: robot-config-service.service
    enabled: true
    daemon_reload: true
