apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-image-puller
data:
  IMAGES: |
    object-detection-v2-1-0=quay.io/cloud-native-robotz-hackathon/workbench-object-detection:v2.1.0;
    object-detection-runtime-v2-1-0=quay.io/mmurakam/runtimes:object-detection-v2.1.0;
    code-rhel9=registry.redhat.io/devspaces/code-rhel9@sha256:5c94e2cb003be58873ad9d90fe695da7633cafe435a164e330b43cff7430e63c;
    devworkspace-project-clone-rhel9=registry.redhat.io/devworkspace/devworkspace-project-clone-rhel9@sha256:afa28466d9b8c9d6421bb7789bccb68ecde9ea2c38617825e75c53ba357d4b76;
    udi-rhel8=registry.redhat.io/devspaces/udi-rhel8@sha256:bc5d28c434089a312ab0944662e7702481ca4e898ef278cf61c0f683f35718df;
    s3-browser-v1-2-0=quay.io/rh-aiservices-bu/odh-tec:1.2.0;
    openvino-model0-server=quay.io/modh/openvino_model_server@sha256:428c00232cbf3b38a3929a0d22d0e13c6388ce353e3853cc2956d175eacf6724;
    odh-modelmesh-runtime-adapter-rhel8=registry.redhat.io/rhoai/odh-modelmesh-runtime-adapter-rhel8@sha256:2d4636ad760ea3a2ef2e85af2b4f2095d61c56c3fd367503bd9fadda74835e7e;
    object-detection-pipeline-runtime-v2-2-5=quay.io/cloud-native-robotz-hackathon/pipeline-runtime-image:v2.25;
  DAEMONSET_NAME: image-puller
  CACHING_INTERVAL_HOURS: "1"
  NAMESPACE: image-puller
  CACHING_MEMORY_REQUEST: 10Mi
  CACHING_MEMORY_LIMIT: 20Mi
  CACHING_CPU_REQUEST: ".05"
  CACHING_CPU_LIMIT: ".2"
  NODE_SELECTOR: |
    {
      "node-role.kubernetes.io/worker": "",
      "kubernetes.io/arch": "amd64"
    }
  IMAGE_PULL_SECRETS: ""
  AFFINITY: "{}"
  KIP_IMAGE: quay.io/eclipse/kubernetes-image-puller:a9ab712
  TOLERATIONS: "[]"
