---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-image-puller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-daemonset
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - watch
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-daemonset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-daemonset
subjects:
- kind: ServiceAccount
  name: k8s-image-puller

