kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: web
  labels:
    app: hub-controller
    app.kubernetes.io/instance: hub-controller
spec:
  to:
    kind: Service
    name: hub-controller
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

