apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-controller
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: edge-gateway/hub-controller/
    repoURL: https://github.com/cloud-native-robotz-hackathon/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
