apiVersion: v1
kind: Secret
metadata:
  name: hub-controller-config
  namespace: hub-controller
stringData:
  DASHBOARD_PASSWORD: "{{ .Values.api_password }}"
  MAP: |
    {
      "robot-dummy": "robot-dummy.default.svc.cluster.local."
    }
type: Opaque