apiVersion: v1
kind: Secret
metadata:
  name: repo-updater-config
  namespace: hub-controller
type: Opaque
stringData:
  RU_ROBOT_NAMES: {{ range $i, $value := .Values.team_robot_map }}{{ $value.robot_name }} {{ end }}
  {{- if .Values.ru_repo_url }}
  RU_REPO_URL: {{ .Values.ru_repo_url }}
  {{- end }}
  {{- if .Values.ru_repo_token }}
  RU_REPO_TOKEN: {{ .Values.ru_repo_token }}
  {{- end }}
