apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web
spec:
  path: /
  to:
    kind: Service
    name: label-studio
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect