---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: label-studio-data
  namespace: {{ .Values.namespacePermissions.user }}-label-studio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-cephfs
