apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: codellama
    serving.kserve.io/deploymentMode: RawDeployment
  name: codellama
  namespace: code-assistant
  finalizers:
    - odh.inferenceservice.finalizers
    - inferenceservice.finalizers
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--max-model-len=8192'
        - '--gpu-memory-utilization=0.9'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: '1'
      runtime: codellama
      storageUri: oci://registry.redhat.io/rhelai1/modelcar-granite-8b-code-instruct:1.4
      #storage:
      #  key: workbench-bucket-ai-connection
      #  path: codellama
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
