---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: object-detection-training-pvc
  namespace: {{ .Values.namespacePermissions.user }}-ai
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-cephfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-memory-pvc
  namespace: {{ .Values.namespacePermissions.user }}-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem