---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: object-detection-training-pvc
  namespace: {{ .Values.namespacePermissions.user }}-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
