apiVersion: batch/v1
kind: Job
metadata:
  name: populate-backup-model
  namespace: {{ .Values.namespacePermissions.user }}-ai
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: populate-backup-model
  template:
    metadata:
      labels:
        app: populate-backup-model
    spec:
      restartPolicy: Never
      containers:
      - name: upload
        image: quay.io/cloud-native-robotz-hackathon/model-container:trained-uploader-1.25.83-20250701T092029
        envFrom:
        - secretRef:
            name: workbench-bucket-ai-connection
  backoffLimit: 4

