apiVersion: batch/v1
kind: Job
metadata:
  name: populate-backup-model
  namespace: {{ .Values.namespacePermissions.user }}-ai
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: upload
        image: quay.io/cloud-native-robotz-hackathon/model-container:trained-uploader-1.25.83
        envFrom:
        - secretRef:
            name: workbench-bucket-ai-connection
        command:
        - /bin/sh
        - -c
        - |
          set -x
          aws configure list
          aws s3 --no-verify-ssl cp \
            /model/robot_onnx/1/model.onnx \
            s3://$AWS_S3_BUCKET/backup/model-latest.onnx \
            --endpoint-url $AWS_S3_ENDPOINT
  backoffLimit: 4

