---

- name: Create own kubeconfig directory
  file:
    state: directory
    path: "{{ new_kubeconfig_dir }}/config/"
    mode: 0755

- name: Copy kubeconfig
  copy:
    src: "{{ kubeconfig_dir }}/config"
    dest: "{{ new_kubeconfig_dir }}/config/kubeconfig"
    remote_src: yes
    mode: 0644

- name: Slurp kubeconfig
  ansible.builtin.slurp:
    src: "{{ new_kubeconfig_dir }}/config/kubeconfig"
  register: kubeconfig_raw

- name: Copy content into kubeconfig
  set_fact:
    kubeconfig: "{{ kubeconfig_raw['content'] | b64decode | from_yaml }}"

- name: Select cluster & user
  set_fact:
    cluster: "{{ kubeconfig | json_query('clusters[?name==`'~ cluster_name ~'`].cluster') | first }}"
    user: "{{ kubeconfig | json_query('users[?name==`admin`].user') | first }}"

- name: Set kube variables
  set_fact:
    k8s_kubeconfig: "{{ new_kubeconfig_dir }}/config/kubeconfig"
    k8s_host: "{{ cluster.server }}"
    k8s_ca_cert: "{{ new_kubeconfig_dir }}/config/ca.crt"
    k8s_client_key: "{{ new_kubeconfig_dir }}/config/client.key"
    k8s_client_cert: "{{ new_kubeconfig_dir }}/config/client.crt"

- name: Create k8s_ca_cert
  copy:
    content: "{{ cluster['certificate-authority-data'] | b64decode }}"
    dest: "{{ k8s_ca_cert }}"
    mode: 0644

- name: Create k8s_client_key
  copy:
    content: "{{ user['client-key-data'] | b64decode }}"
    dest: "{{ k8s_client_key }}"
    mode: 0644

- name: Create k8s_client_cert
  copy:
    content: "{{ user['client-certificate-data'] | b64decode }}"
    dest: "{{ k8s_client_cert }}"
    mode: 0644