apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: openshift-operators
spec:
  config:
    env:
    - name: CLUSTER_PERMISSIONS_ALLOWED
      value: "true"
  channel: stable
  installPlanApproval: Automatic
  name: skupper-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
