apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.team }}-robot-gitops"
  namespace: openshift-gitops
spec:
  destination:
    server: "https://{{ .Values.robot_name }}.robot.svc.cluster.local.:6443"
  project: "{{ .Values.team }}"
  source:
    path: base/
    repoURL: "https://gitea.{{ .Values.openshift_cluster_ingress_domain }}/{{ .Values.team }}/robot-gitops.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
