apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:container-build
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - container-build
  resources:
  - securitycontextconstraints
  verbs:
  - use
