apiVersion: v1
kind: Service
metadata:
  labels:
    app: hub-controller-live
  name: hub-controller-live
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hub-controller-live
  type: ClusterIP
