---
- hosts: rhpdsclusters
  vars_files:
  - ../vars.yml
  tasks:
  - import_role:
      name: prepare-host
      tasks_from: prepare-host.yml

- hosts: localhost
  connection: local
  tasks:
  - import_role:
      name: prepare-host
      tasks_from: install-openshift-client.yml
  tags:
    - prepare
