kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-url: https://github.com/cloud-native-robotz-hackathon/infrastructure/tree/main/container-images/workbench-object-detection
    opendatahub.io/notebook-image-name: "Object detection"
    opendatahub.io/notebook-image-order: "1"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling computer vision use cases, in particular object detection.
  name: object-detection
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
    app.opendatahub.io/workbenches: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2.1.0"
      from:
        kind: DockerImage
        name: quay.io/cloud-native-robotz-hackathon/workbench-object-detection:v2.1.0
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-build-commit: 38a4f33
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"opencv","version":"4.8.0.74"},{"name":"ultralytics","version":"8.0.130"},{"name":"onnxruntime","version":"1.15.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
        opendatahub.io/workbench-image-recommended: "true"  
