apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hub-controller
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
