---
- hosts: robots
  gather_facts: true
  vars:
    edge_controller_version: v2.1.1
  handlers:
    - name: restart edge-controller
      ansible.builtin.systemd:
        name: edge-controller.service
        state: restarted
        daemon_reload: true
  tasks:
    - name: Slurp /robot-image-version
      ansible.builtin.slurp:
        src: /robot-image-version
      register: robot_image_version

    - name: Check robot image version
      fail:
        msg: "Please check robot image version"
      #when: robot_image_version['content'] | b64decode == robot-hackathon-image.20240726
      when: robot_image_version['content'] != "cm9ib3QtaGFja2F0aG9uLWltYWdlLjIwMjQwNzI2Cg=="

    - name: Stop and remove edgehub.service systemd unit
      ignore_errors: true
      ansible.builtin.systemd:
        name: edgehub.service
        force: true
        state: stopped

    # Remove old edge-controller aka edgehub
    - name: Remove old edge-controller aka edgehub
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /lib/systemd/system/edgehub.service
        - /usr/local/bin/edgehub.py

    - name: Rollout new version of edge-controller "{{ edge_controller_version  }}"
      ansible.builtin.git:
        repo: https://github.com/cloud-native-robotz-hackathon/edge-controller
        dest: /opt/edge-controller
        version: "{{ edge_controller_version  }}"
      register: git_result

    - name: Install systemd.service
      ansible.builtin.copy:
        remote_src: true
        src: /opt/edge-controller/edge-controller.service
        dest: /etc/systemd/system/edge-controller.service
        mode: '0644'

    - name: Enable edge-controller service
      ansible.builtin.systemd:
        name: edge-controller.service
        enabled: true
        daemon_reload: true

    - name: Restart edge-controller
      ansible.builtin.systemd:
        name: edge-controller.service
        state: restarted
        daemon_reload: true
      when: git_result.changed

    - name: Check version
      ansible.builtin.uri:
        url: "http://{{ansible_host}}:5000/version"
        method: GET
        return_content: true
        status_code:
          - 200
      register: version_check
      until: version_check is not failed and edge_controller_version in version_check.content
      retries: 10
      delay: 2

    - name: Rollout /etc/issue
      ansible.builtin.copy:
        content: |
          Ubuntu 22.04.4 LTS \n \l
          eth0: \4{eth0}
          wlan0: \4{wlan0}
        dest: /etc/issue

    - name: Rollout /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        search_string: "{{ ansible_default_ipv4.address }}"
        line: "{{ ansible_default_ipv4.address }} robot.local {{ inventory_hostname }}"
        owner: root
        group: root
        mode: '0644'

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

