---
- hosts: robots
  gather_facts: false
  tasks:
    - name: Stop microshift
      ansible.builtin.systemd_service:
        state: stopped
        name: microshift.service

    - name: Clean /var/lib/microshift
      ansible.builtin.file:
        state: absent
        path: /var/lib/microshift

    - name: Start microshift
      ansible.builtin.systemd_service:
        state: started
        name: microshift.service

    - name: Wait for /var/lib/microshift/resources/kubeadmin/kubeconfig
      ansible.builtin.wait_for:
        path: /var/lib/microshift/resources/kubeadmin/kubeconfig
        state: present
        msg: Timeout to find file kubeconfig

    - name: ~/.kube/
      ansible.builtin.file:
        state: directory
        path: ~/.kube/

    - name: Install kubeconfig to root user
      ansible.builtin.copy:
        src: "/var/lib/microshift/resources/kubeadmin/kubeconfig"
        dest: "~/.kube/config"
        remote_src: yes

    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: "/var/lib/microshift/resources/kubeadmin/kubeconfig"
        dest: "kubeconfig-{{ inventory_hostname }}"
        flat: yes

    - name: Adjust kubeconfig
      connection: local
      ansible.builtin.shell:

        export KUBECONFIG=kubeconfig-{{ inventory_hostname }};
        export ROBOT={{ inventory_hostname.split('.') | first }};
        kubectl config set-cluster ${ROBOT} --server=https://{{ inventory_hostname }}:6443 --insecure-skip-tls-verify=true;
        kubectl config set-context ${ROBOT} --user=user --cluster=${ROBOT};
        kubectl config use-context ${ROBOT};

    - name: Wait for api
      ansible.builtin.wait_for:
        port: 6443

    - name: Info
      ansible.builtin.debug:
        msg: "Run export KUBECONFIG=kubeconfig-{{ inventory_hostname }}; to have oc/kubectl access."
