---
- hosts: robots
  gather_facts: true
  tasks:
    - name: Reset MicroShift
      ansible.builtin.include_role:
        name: robot
        tasks_from: reset-microshift.yaml

    - name: Wait for api
      ansible.builtin.wait_for:
        port: 6443

    - name: Info
      ansible.builtin.debug:
        msg: "Run export KUBECONFIG=kubeconfig-{{ inventory_hostname }}; to have oc/kubectl access."
