---
# Prepare the data-center
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Restart skupper-site-controller
      kubernetes.core.k8s:
        state: absent
        kubeconfig: "kubeconfig-data-center"
        namespace: openshift-operators
        api_version: v1
        kind: Pod
        label_selectors:
          - app.kubernetes.io/name=skupper-site-controller
        wait_condition:
          type: Ready
          status: 'True'

    - name: Destroy a namespaces
      kubernetes.core.k8s:
        state: absent
        wait: true
        kubeconfig: "kubeconfig-data-center"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: robot
          spec: {}

    - name: Create a namespaces
      kubernetes.core.k8s:
        state: present
        wait: true
        kubeconfig: "kubeconfig-data-center"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: robot
          spec: {}

    - name: Start skupper at data-center
      kubernetes.core.k8s:
        state: present
        kubeconfig: "kubeconfig-data-center"
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: skupper-site
            namespace: robot
          data:
            cluster-permissions: "false"
            console: "true"
            console-authentication: internal
            console-password: ""
            console-user: ""
            enable-skupper-events: "true"
            flow-collector: "true"
            ingress: route
            name: data-center
            router-console: "false"
            router-logging: ""
            router-mode: interior
            service-controller: "true"
            service-sync: "true"

    - name: Wait for skupper-site
      kubernetes.core.k8s_info:
        kubeconfig: "kubeconfig-data-center"
        namespace: "robot"
        api_version: v1
        kind: Pods
        label_selectors:
          app.kubernetes.io/part-of=skupper
        wait: true
        wait_condition:
          type: Ready

- hosts: robots
  gather_facts: false
  tasks:

    # - name: Reset MicroShift
    #   ansible.builtin.include_role:
    #     name: robot
    #     tasks_from: reset-microshift.yaml

    - name: Download kubeconfig
      ansible.builtin.include_role:
        name: robot
        tasks_from: download-kubeconfig.yaml

    - name: Destroy skupper a namespaces 
      delegate_to: localhost
      kubernetes.core.k8s:
        state: absent
        wait: true
        kubeconfig: "kubeconfig-{{ inventory_hostname }}"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: skupper
          spec: {}

    - name: Create skupper a namespaces 
      delegate_to: localhost
      kubernetes.core.k8s:
        state: present
        wait: true
        kubeconfig: "kubeconfig-{{ inventory_hostname }}"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: skupper
          spec: {}
    
    - name: Download skupper
      ansible.builtin.get_url:
        url: https://github.com/skupperproject/skupper/releases/download/1.8.3/skupper-cli-1.8.3-linux-arm64.tgz
        dest: /tmp/skupper.tgz
        checksum: md5:6950f429a712fcd6cec0d67bc87a6f2f

    - name: Unarchive skupper
      ansible.builtin.unarchive:
        src: /tmp/skupper.tgz
        dest: /usr/local/bin
        remote_src: yes

    - name: Init Skupper
      ansible.builtin.shell:
        cmd: "/usr/local/bin/skupper init --ingress none --namespace skupper --site-name {{ inventory_hostname }}"

    - name: Token request for robot
      delegate_to: localhost
      kubernetes.core.k8s:
        state: present
        kubeconfig: "kubeconfig-data-center"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            namespace: robot
            labels:
              skupper.io/type: connection-token-request
            name: "{{ inventory_hostname }}"

    - name: Fetch secret from data-center
      delegate_to: localhost
      kubernetes.core.k8s_info:
        kubeconfig: "kubeconfig-data-center"
        api_version: v1
        kind: Secret
        name: "{{ inventory_hostname }}"
        namespace: robot
      register: token_secret
      retries: 10
      until: token_secret.resources[0].metadata.labels['skupper.io/type'] == "connection-token"

    - name: Extract & change token
      ansible.builtin.set_fact:
        token: "{{ token_secret.resources[0] | combine(to_change, recursive=true)  }}"
      vars:
        to_change:
          metadata:
            namespace: skupper
            resourceVersion:
            uid:
            creationTimestamp:

    - name: Apply token at robot
      delegate_to: localhost
      kubernetes.core.k8s:
        state: present
        kubeconfig: "kubeconfig-{{ inventory_hostname  }}"
        definition: "{{ token  }}"

    - name: Deploy reverse proxy
      delegate_to: localhost
      kubernetes.core.k8s:
        state: present
        kubeconfig: "kubeconfig-{{ inventory_hostname  }}"
        wait: yes
        wait_condition:
          type: Available
          status: "True"
          reason: MinimumReplicasAvailable
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ inventory_hostname }}"
            namespace: skupper
            labels:
              app: reverse-proxy
              app.openshift.io/runtime: traefik
              app.kubernetes.io/part-of: reverse-proxy
          spec:
            replicas: 1
            strategy:
              type: Recreate
            selector:
              matchLabels:
                app: reverse-proxy
            template:
              metadata:
                labels:
                  app: reverse-proxy
              spec:
                automountServiceAccountToken: false
                containers:
                  - image: quay.io/cloud-native-robotz-hackathon/ubi-traefik:20250323T171302
                    name: traefik
                    ports:
                      - name: edge-controller
                        containerPort: 5000
                      - name: k8s-api
                        containerPort: 6443
                    env:
                      - name: HOST_IP
                        valueFrom:
                          fieldRef:
                            fieldPath: status.hostIP        

      # skupper expose deployment --namespace skupper reverse-proxy
      # deployment reverse-proxy exposed as reverse-proxy
    - name: Expose reverse-proxy
      ansible.builtin.shell:
        cmd: "/usr/local/bin/skupper expose deployment --namespace skupper {{ inventory_hostname }}"

    # - name: Expose hub-controll-live via route for testing purpose
    #   kubernetes.core.k8s:
    #     state: present
    #     kubeconfig: "kubeconfig-data-center"
    #     definition:
    #       apiVersion: route.openshift.io/v1
    #       kind: Route
    #       metadata:
    #         name: thbc
    #         namespace: red-hat-service-interconnect-data-center
    #       spec:
    #         port:
    #           targetPort: port8080
    #         tls:
    #           insecureEdgeTerminationPolicy: Redirect
    #           termination: edge
    #         to:
    #           kind: Service
    #           name: hub-controller-live
    #           weight: 100
    #         wildcardPolicy: None

    # - name: Wait for hub-controller-live service
    #   tags:
    #     - check
    #   kubernetes.core.k8s_info:
    #     kubeconfig: "kubeconfig-data-center"
    #     namespace: "red-hat-service-interconnect-data-center"
    #     api_version: v1
    #     kind: Service
    #     name: hub-controller-live
    #     wait: true

    # - name: Run check pod
    #   tags:
    #     - check
    #   kubernetes.core.k8s:
    #     state: present
    #     kubeconfig: "kubeconfig-data-center"
    #     wait: true
    #     wait_condition:
    #       type: Initialized
    #       reason: "PodCompleted"
    #     definition:
    #       apiVersion: v1
    #       kind: Pod
    #       metadata:
    #         generateName: check-skupper-connect
    #         namespace: red-hat-service-interconnect-data-center
    #       spec:
    #         restartPolicy: Never
    #         containers:
    #           - name: checker
    #             image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    #             command:
    #               - "/bin/sh"
    #               - "-c"
    #               - |
    #                   set -x
    #                   curl http://hub-controller-live.red-hat-service-interconnect-data-center.svc.cluster.local:8080/