apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hub-controller-live
  type: ClusterIP
