apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hub-controller-live
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  annotations:
    app.openshift.io/vcs-uri: git@github.com:cloud-native-robotz-hackathon/hubcontroller-rest-quarkus.git
    app.quarkus.io/vcs-uri: https://github.com/cloud-native-robotz-hackathon/hubcontroller-rest-quarkus.git
  name: hub-controller-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-controller-live
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hub-controller-live
    spec:
      containers:
      - env:
        - name: MAP
          valueFrom:
            configMapKeyRef:
              key: MAP
              name: robot-mapping-configmap
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/cloud-native-robotz-hackathon/hubcontroller-rest-quarkus:latest-native
        imagePullPolicy: IfNotPresent
        name: hub-controller

