---

- name: Create Quay Namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'quay-namespace.yml' ) | from_yaml }}"
  tags:
    - quay


- name: Create Quay OperatorGroup
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'operator-group.yml' ) | from_yaml }}"
  tags:
    - quay

- name: Install Quay Operator Subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'quay-operator.yml' ) | from_yaml }}"
  tags:
    - quay


- name: Remove quay LimitRanges 
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'quay-limit-range.yml' ) | from_yaml }}"
  tags:
    - quay

- name: "Wait for Nooba StrorageClass to be present"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    api_version: "storage.k8s.io/v1"
    kind: StorageClass
    name: openshift-storage.noobaa.io
  register: nooba_storageclass
  retries: 30
  delay: 10
  until: nooba_storageclass.resources | list | length == 1
  tags:
    - quay

- name: Install Quay Instance
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    definition: "{{ lookup('file', 'quay-instance.yml' ) | from_yaml }}"
  tags:
    - quay

- name: Include Quay Bridge Operator
  include_tasks: "install-quay-bridge.yml"
  tags:
    - quay


